name: PHP Linter

on: [pull_request, push]
jobs:
  build:
    name: Apply lint and PHP validation.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PHP: true
          VALIDATE_PHP_PHPCS: true
